#!/bin/bash

# Navigate to the compiled assets directory
# Pre-compiled assets are usually in build/web/assets/assets/
TARGET_DIR="build/web/assets"
mkdir -p $TARGET_DIR

echo "Generating .env file in $TARGET_DIR from Heroku Config Vars..."

# Create the .env file from Heroku Config Vars
echo "FIREBASE_API_KEY=$FIREBASE_API_KEY" > $TARGET_DIR/.env
echo "FIREBASE_APP_KEY=$FIREBASE_APP_KEY"
echo "FIREBASE_APP_ID=$FIREBASE_APP_ID" >> $TARGET_DIR/.env
echo "FIREBASE_APP_ID=$FIREBASE_APP_ID"
echo "FIREBASE_MESSAGING_SENDER_ID=$FIREBASE_MESSAGING_SENDER_ID" >> $TARGET_DIR/.env
echo "FIREBASE_MESSAGING_SENDER_ID=$FIREBASE_MESSAGING_SENDER_ID"
echo "FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID" >> $TARGET_DIR/.env
echo "FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID"
echo "FIREBASE_AUTH_DOMAIN=$FIREBASE_AUTH_DOMAIN" >> $TARGET_DIR/.env
echo "FIREBASE_AUTH_DOMAIN=$FIREBASE_AUTH_DOMAIN"
echo "FIREBASE_STORAGE_BUCKET=$FIREBASE_STORAGE_BUCKET" >> $TARGET_DIR/.env
echo "FIREBASE_STORAGE_BUCKET=$FIREBASE_STORAGE_BUCKET"
echo "FIREBASE_MEASUREMENT_ID=$FIREBASE_MEASUREMENT_ID" >> $TARGET_DIR/.env
echo "API_BASE_DEV_URL=$API_BASE_DEV_URL" >> $TARGET_DIR/.env
echo "API_BASE_DEV_URL=$API_BASE_DEV_URL"

echo ".env file generated in $TARGET_DIR"
