// Mocks generated by Mockito 5.4.6 from annotations
// in t4g_for_business/test/features/auth/presentation/controllers/login_controller_test_fixed.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i10;

import 'package:flutter/widgets.dart' as _i2;
import 'package:get/get.dart' as _i3;
import 'package:get/get_state_manager/src/simple/list_notifier.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:t4g_for_business/features/auth/domain/entities/user.dart'
    as _i6;
import 'package:t4g_for_business/features/auth/domain/usecases/interface/login.dart'
    as _i4;
import 'package:t4g_for_business/features/auth/presentation/presenters/interface/login.presenter.dart'
    as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTextEditingController_0 extends _i1.SmartFake
    implements _i2.TextEditingController {
  _FakeTextEditingController_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInternalFinalCallback_1<T> extends _i1.SmartFake
    implements _i3.InternalFinalCallback<T> {
  _FakeInternalFinalCallback_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTextSelection_2 extends _i1.SmartFake implements _i2.TextSelection {
  _FakeTextSelection_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTextEditingValue_3 extends _i1.SmartFake
    implements _i2.TextEditingValue {
  _FakeTextEditingValue_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTextSpan_4 extends _i1.SmartFake implements _i2.TextSpan {
  _FakeTextSpan_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);

  @override
  String toString({_i2.DiagnosticLevel? minLevel = _i2.DiagnosticLevel.info}) =>
      super.toString();
}

/// A class which mocks [LoginUseCaseInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginUseCaseInterface extends _i1.Mock
    implements _i4.LoginUseCaseInterface {
  MockLoginUseCaseInterface() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i6.UserEntity?> execute(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [email, password]),
            returnValue: _i5.Future<_i6.UserEntity?>.value(),
          )
          as _i5.Future<_i6.UserEntity?>);

  @override
  _i5.Future<_i6.UserEntity?> signInWithGoogle(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithGoogle, [email, password]),
            returnValue: _i5.Future<_i6.UserEntity?>.value(),
          )
          as _i5.Future<_i6.UserEntity?>);

  @override
  _i5.Future<bool> requestPasswordReset(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#requestPasswordReset, [email]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);
}

/// A class which mocks [LoginPresenterInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginPresenterInterface extends _i1.Mock
    implements _i7.LoginPresenterInterface {
  MockLoginPresenterInterface() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  bool get isEmailValid =>
      (super.noSuchMethod(Invocation.getter(#isEmailValid), returnValue: false)
          as bool);

  @override
  bool get isPasswordValid =>
      (super.noSuchMethod(
            Invocation.getter(#isPasswordValid),
            returnValue: false,
          )
          as bool);

  @override
  bool get obscurePassword =>
      (super.noSuchMethod(
            Invocation.getter(#obscurePassword),
            returnValue: false,
          )
          as bool);

  @override
  bool get isForgotPasswordMode =>
      (super.noSuchMethod(
            Invocation.getter(#isForgotPasswordMode),
            returnValue: false,
          )
          as bool);

  @override
  bool get isResetEmailSent =>
      (super.noSuchMethod(
            Invocation.getter(#isResetEmailSent),
            returnValue: false,
          )
          as bool);

  @override
  String get resetEmail =>
      (super.noSuchMethod(
            Invocation.getter(#resetEmail),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#resetEmail),
            ),
          )
          as String);

  @override
  _i2.TextEditingController get emailController =>
      (super.noSuchMethod(
            Invocation.getter(#emailController),
            returnValue: _FakeTextEditingController_0(
              this,
              Invocation.getter(#emailController),
            ),
          )
          as _i2.TextEditingController);

  @override
  _i2.TextEditingController get passwordController =>
      (super.noSuchMethod(
            Invocation.getter(#passwordController),
            returnValue: _FakeTextEditingController_0(
              this,
              Invocation.getter(#passwordController),
            ),
          )
          as _i2.TextEditingController);

  @override
  _i2.TextEditingController get resetEmailController =>
      (super.noSuchMethod(
            Invocation.getter(#resetEmailController),
            returnValue: _FakeTextEditingController_0(
              this,
              Invocation.getter(#resetEmailController),
            ),
          )
          as _i2.TextEditingController);

  @override
  set isLoading(bool? value) => super.noSuchMethod(
    Invocation.setter(#isLoading, value),
    returnValueForMissingStub: null,
  );

  @override
  set isEmailValid(bool? value) => super.noSuchMethod(
    Invocation.setter(#isEmailValid, value),
    returnValueForMissingStub: null,
  );

  @override
  set isPasswordValid(bool? value) => super.noSuchMethod(
    Invocation.setter(#isPasswordValid, value),
    returnValueForMissingStub: null,
  );

  @override
  set obscurePassword(bool? value) => super.noSuchMethod(
    Invocation.setter(#obscurePassword, value),
    returnValueForMissingStub: null,
  );

  @override
  set isForgotPasswordMode(bool? value) => super.noSuchMethod(
    Invocation.setter(#isForgotPasswordMode, value),
    returnValueForMissingStub: null,
  );

  @override
  set isResetEmailSent(bool? value) => super.noSuchMethod(
    Invocation.setter(#isResetEmailSent, value),
    returnValueForMissingStub: null,
  );

  @override
  set resetEmail(String? value) => super.noSuchMethod(
    Invocation.setter(#resetEmail, value),
    returnValueForMissingStub: null,
  );

  @override
  _i3.InternalFinalCallback<void> get onStart =>
      (super.noSuchMethod(
            Invocation.getter(#onStart),
            returnValue: _FakeInternalFinalCallback_1<void>(
              this,
              Invocation.getter(#onStart),
            ),
          )
          as _i3.InternalFinalCallback<void>);

  @override
  _i3.InternalFinalCallback<void> get onDelete =>
      (super.noSuchMethod(
            Invocation.getter(#onDelete),
            returnValue: _FakeInternalFinalCallback_1<void>(
              this,
              Invocation.getter(#onDelete),
            ),
          )
          as _i3.InternalFinalCallback<void>);

  @override
  bool get initialized =>
      (super.noSuchMethod(Invocation.getter(#initialized), returnValue: false)
          as bool);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  int get listeners =>
      (super.noSuchMethod(Invocation.getter(#listeners), returnValue: 0)
          as int);

  @override
  void togglePasswordVisibility() => super.noSuchMethod(
    Invocation.method(#togglePasswordVisibility, []),
    returnValueForMissingStub: null,
  );

  @override
  bool validateForm(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#validateForm, [email, password]),
            returnValue: false,
          )
          as bool);

  @override
  bool validateEmail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#validateEmail, [email]),
            returnValue: false,
          )
          as bool);

  @override
  void resetToLoginMode() => super.noSuchMethod(
    Invocation.method(#resetToLoginMode, []),
    returnValueForMissingStub: null,
  );

  @override
  void update([List<Object>? ids, bool? condition = true]) =>
      super.noSuchMethod(
        Invocation.method(#update, [ids, condition]),
        returnValueForMissingStub: null,
      );

  @override
  void onInit() => super.noSuchMethod(
    Invocation.method(#onInit, []),
    returnValueForMissingStub: null,
  );

  @override
  void onReady() => super.noSuchMethod(
    Invocation.method(#onReady, []),
    returnValueForMissingStub: null,
  );

  @override
  void onClose() => super.noSuchMethod(
    Invocation.method(#onClose, []),
    returnValueForMissingStub: null,
  );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
    Invocation.method(#$configureLifeCycle, []),
    returnValueForMissingStub: null,
  );

  @override
  _i9.Disposer addListener(_i9.GetStateUpdate? listener) =>
      (super.noSuchMethod(
            Invocation.method(#addListener, [listener]),
            returnValue: () {},
          )
          as _i9.Disposer);

  @override
  void removeListener(_i10.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void refresh() => super.noSuchMethod(
    Invocation.method(#refresh, []),
    returnValueForMissingStub: null,
  );

  @override
  void refreshGroup(Object? id) => super.noSuchMethod(
    Invocation.method(#refreshGroup, [id]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyChildrens() => super.noSuchMethod(
    Invocation.method(#notifyChildrens, []),
    returnValueForMissingStub: null,
  );

  @override
  void removeListenerId(Object? id, _i10.VoidCallback? listener) =>
      super.noSuchMethod(
        Invocation.method(#removeListenerId, [id, listener]),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i9.Disposer addListenerId(Object? key, _i9.GetStateUpdate? listener) =>
      (super.noSuchMethod(
            Invocation.method(#addListenerId, [key, listener]),
            returnValue: () {},
          )
          as _i9.Disposer);

  @override
  void disposeId(Object? id) => super.noSuchMethod(
    Invocation.method(#disposeId, [id]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [TextEditingController].
///
/// See the documentation for Mockito's code generation for more information.
class MockTextEditingController extends _i1.Mock
    implements _i2.TextEditingController {
  MockTextEditingController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get text =>
      (super.noSuchMethod(
            Invocation.getter(#text),
            returnValue: _i8.dummyValue<String>(this, Invocation.getter(#text)),
          )
          as String);

  @override
  _i2.TextSelection get selection =>
      (super.noSuchMethod(
            Invocation.getter(#selection),
            returnValue: _FakeTextSelection_2(
              this,
              Invocation.getter(#selection),
            ),
          )
          as _i2.TextSelection);

  @override
  set text(String? newText) => super.noSuchMethod(
    Invocation.setter(#text, newText),
    returnValueForMissingStub: null,
  );

  @override
  set value(_i2.TextEditingValue? newValue) => super.noSuchMethod(
    Invocation.setter(#value, newValue),
    returnValueForMissingStub: null,
  );

  @override
  set selection(_i2.TextSelection? newSelection) => super.noSuchMethod(
    Invocation.setter(#selection, newSelection),
    returnValueForMissingStub: null,
  );

  @override
  _i2.TextEditingValue get value =>
      (super.noSuchMethod(
            Invocation.getter(#value),
            returnValue: _FakeTextEditingValue_3(
              this,
              Invocation.getter(#value),
            ),
          )
          as _i2.TextEditingValue);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i2.TextSpan buildTextSpan({
    required _i2.BuildContext? context,
    _i2.TextStyle? style,
    required bool? withComposing,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#buildTextSpan, [], {
              #context: context,
              #style: style,
              #withComposing: withComposing,
            }),
            returnValue: _FakeTextSpan_4(
              this,
              Invocation.method(#buildTextSpan, [], {
                #context: context,
                #style: style,
                #withComposing: withComposing,
              }),
            ),
          )
          as _i2.TextSpan);

  @override
  void clear() => super.noSuchMethod(
    Invocation.method(#clear, []),
    returnValueForMissingStub: null,
  );

  @override
  void clearComposing() => super.noSuchMethod(
    Invocation.method(#clearComposing, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i10.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i10.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
