// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform, kDebugMode;
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:t4g_for_business/utils/helpers/web_env.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
    apiKey:
        kDebugMode
            ? dotenv.env['FIREBASE_API_KEY'] ?? ''
            : WebEnv.getEnv('FIREBASE_API_KEY'),
    appId:
        kDebugMode
            ? dotenv.env['FIREBASE_APP_ID'] ?? ''
            : WebEnv.getEnv('FIREBASE_APP_ID'),
    messagingSenderId:
        kDebugMode
            ? dotenv.env['FIREBASE_MESSAGING_SENDER_ID'] ?? ''
            : WebEnv.getEnv('FIREBASE_MESSAGING_SENDER_ID'),
    projectId:
        kDebugMode
            ? dotenv.env['FIREBASE_PROJECT_ID'] ?? ''
            : WebEnv.getEnv('FIREBASE_PROJECT_ID'),
    authDomain:
        kDebugMode
            ? dotenv.env['FIREBASE_AUTH_DOMAIN'] ?? ''
            : WebEnv.getEnv('FIREBASE_AUTH_DOMAIN'),
    storageBucket:
        kDebugMode
            ? dotenv.env['FIREBASE_STORAGE_BUCKET'] ?? ''
            : WebEnv.getEnv('FIREBASE_STORAGE_BUCKET'),
    measurementId:
        kDebugMode
            ? dotenv.env['FIREBASE_MEASUREMENT_ID'] ?? ''
            : WebEnv.getEnv('FIREBASE_MEASUREMENT_ID'),
  );
}
