// Mocks generated by Mockito 5.4.6 from annotations
// in t4g_for_business/test/features/auth/domain/usecases/login_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:t4g_for_business/features/auth/data/repositories/interface/login.dart'
    as _i2;
import 'package:t4g_for_business/features/auth/domain/entities/user.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [LoginRepositoryInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginRepositoryInterface extends _i1.Mock
    implements _i2.LoginRepositoryInterface {
  MockLoginRepositoryInterface() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.UserEntity?> login(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#login, [email, password]),
            returnValue: _i3.Future<_i4.UserEntity?>.value(),
          )
          as _i3.Future<_i4.UserEntity?>);

  @override
  _i3.Future<_i4.UserEntity?> signInWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithGoogle, []),
            returnValue: _i3.Future<_i4.UserEntity?>.value(),
          )
          as _i3.Future<_i4.UserEntity?>);

  @override
  _i3.Future<void> resetPassword(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [email]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
