// Mocks generated by Mockito 5.4.5 from annotations
// in t4g_for_business/test/features/product_managment/presentation/controllers/product_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:t4g_for_business/features/product_managment/data/models/barcode/index.dart'
    as _i2;
import 'package:t4g_for_business/features/product_managment/data/usecase/product_management_usecase.interface.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBarcodeModel_0 extends _i1.SmartFake implements _i2.BarcodeModel {
  _FakeBarcodeModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBarcodeResultModel_1 extends _i1.SmartFake
    implements _i2.BarcodeResultModel {
  _FakeBarcodeResultModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ProductManagementUseCaseInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductManagementUseCaseInterface extends _i1.Mock
    implements _i3.ProductManagementUseCaseInterface {
  MockProductManagementUseCaseInterface() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.BarcodeModel> getProducts(
    String? token, {
    int? perPage = 10,
    int? page = 1,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProducts,
          [token],
          {
            #perPage: perPage,
            #page: page,
          },
        ),
        returnValue: _i4.Future<_i2.BarcodeModel>.value(_FakeBarcodeModel_0(
          this,
          Invocation.method(
            #getProducts,
            [token],
            {
              #perPage: perPage,
              #page: page,
            },
          ),
        )),
      ) as _i4.Future<_i2.BarcodeModel>);

  @override
  _i4.Future<_i2.BarcodeResultModel> createProduct(
    _i2.BarcodeResultModel? product,
    String? token,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createProduct,
          [
            product,
            token,
          ],
        ),
        returnValue:
            _i4.Future<_i2.BarcodeResultModel>.value(_FakeBarcodeResultModel_1(
          this,
          Invocation.method(
            #createProduct,
            [
              product,
              token,
            ],
          ),
        )),
      ) as _i4.Future<_i2.BarcodeResultModel>);

  @override
  _i4.Future<_i2.BarcodeResultModel> updateProduct(
    String? id,
    _i2.BarcodeResultModel? product,
    String? token,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProduct,
          [
            id,
            product,
            token,
          ],
        ),
        returnValue:
            _i4.Future<_i2.BarcodeResultModel>.value(_FakeBarcodeResultModel_1(
          this,
          Invocation.method(
            #updateProduct,
            [
              id,
              product,
              token,
            ],
          ),
        )),
      ) as _i4.Future<_i2.BarcodeResultModel>);

  @override
  _i4.Future<void> deleteProduct(
    String? id,
    String? token,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteProduct,
          [
            id,
            token,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
